cfg = dict(
    model='LGR_r50_prompt',
    desc_path='data/kinetics400',
    data_root_train='data/kinetics400/videos_train/',
    data_root_val='data/kinetics400/videos_val/',
    pretrained_clip='pretrained/RN50.pt',
    context_length=75,
    pretrain_cvlp=False,
    pretrain_cvlp_path='checkpoints/k400_LT_pretrain_r50',
    loss_type="CE",
    two_branch=True,
    fusion_layers=6,

    use_mcloader=True,
    data_set='Kinetics',
    dataset='Kinetics',
    drop_last=True,
    index_bias=0,
    save_interval=1,
    val_interval=1,

    weight_sample=True,
    use_sqrt_freq=True,
    train_list_file='data/kinetics400/k400_LT_train_videos.txt',
    val_list_file='data/kinetics400/kinetics_video_val_list.txt',

    lr=1e-3,
    min_lr=0,
    warmup_epochs=0,
    text_lr=1e-5,
    alpha=0.1,

    epochs=50,
    batch_size=int(128),
    is_video=True,
    num_segments=8,
    new_length=1,
    select_num=50,

    repeated_aug=False,
    clip_ms=True,
    io_backend='disk',
    only_video=False,
    find_unused_parameters=True,
    broadcast_bn_buffer=True,
    num_classes=400,

    opt='adamw',
    sim_header='Transf',
    dropout=0.,
    emb_dropout=0.,
    place='blockres',
    joint=False,
    tsm=False,
    T=8,
    consider_fusion_module=False
)