prompt_templates = [
    'a bad video of a {}.',
    'a video of many {}.',
    'a tape of a {}.',
    'a video of the hard to see {}.',
    'a low resolution video of the {}.',
    'a recording of a {}.',
    'shots of a {}.',
    'a bad video of the {}.',
    'a cropped video of the {}.',
    'a movie of a {}.',
    'the embroidered {}.',
    'a video of a hard to see {}.',
    'a bright video of a {}.',
    'a video of a clean {}.',
    'a video of a dirty {}.',
    'a dark video of the {}.',
    'a clip of a {}.',
    'a video of my {}.',
    'the plastic {}.',
    'a video of the cool {}.',
    'a close-up video of a {}.',
    'a black and white video of the {}.',
    'a film of the {}.',
    'a film of a {}.',
    'a pixelated video of the {}.',
    'a tape of the {}.',
    'a bright video of the {}.',
    'a cropped video of a {}.',
    'a plastic {}.',
    'a video of the dirty {}.',
    'a jpeg corrupted video of a {}.',
    'a blurry video of the {}.',
    'a video of the {}.',
    'a good video of the {}.',
    'a recording of the {}.',
    'a {} in a video game.',
    'a video of one {}.',
    'a doodle animation of a {}.',
    'a close-up video of the {}.',
    'a video of a {}.',
    'the origami {}.',
    'the {} in a video game.',
    'a vlog of a {}.',
    'a doodle animation of the {}.',
    'a origami {}.',
    'a low resolution video of a {}.',
    'the toy {}.',
    'a rendition of the {}.',
    'a video of the clean {}.',
    'a video of a large {}.',
    'a rendition of a {}.',
    'a video of a nice {}.',
    'a video of a weird {}.',
    'a blurry video of a {}.',
    'a cartoon {}.',
    'art of a {}.',
    'a vlog of the {}.',
    'a embroidered {}.',
    'a pixelated video of a {}.',
    'itap of the {}.',
    'a jpeg corrupted video of the {}.',
    'a good video of a {}.',
    'a plushie {}.',
    'a video of the nice {}.',
    'a video of the small {}.',
    'a video of the weird {}.',
    'the cartoon {}.',
    'art of the {}.',
    'a clip of the {}.',
    'a video of the large {}.',
    'a black and white video of a {}.',
    'the plushie {}.',
    'a dark video of a {}.',
    'itap of a {}.',
    'shots of the {}.',
    'a toy {}.',
    'itap of my {}.',
    'a video of a cool {}.',
    'a video of a small {}.',
    'a movie of the {}.',
    "a photo of action {}.",
    "a picture of action {}.",
    "Human action of {}.",
    "{}, an action.",
    "{} this is an action.",
    "{}, a video of action.",
    "Playing action of {}.",
    "{}.",
    "Playing a kind of action, {}.",
    "Doing a kind of action, {}.",
    "Look, the human is {}.",
    "Can you recognize the action of {}?",
    "Video classification of {}.",
    "A video of {}.",
    "The man is {}.",
    "The woman is {}."
]