cfg = dict(
    model='LGR_vit16_prompt',
    desc_path='data/kinetics400_fewshot_C',
    data_root_train='data/kinetics400/',
    data_root_val='data/kinetics400/videos_val/',
    pretrained_clip='pretrained/ViT-B-16.pt',
    context_length=75,
    pretrain_cvlp=False,
    pretrain_cvlp_path='checkpoints/k400_fewshot_C_pretrain_vit16_3p',
    loss_type="CE",
    two_branch=True,

    use_mcloader=True,
    data_set='Kinetics',
    dataset='Kinetics',
    drop_last=True,
    index_bias=0,

    weight_sample=True,
    use_sqrt_freq=True,
    train_list_file='data/kinetics400_fewshot_C/k400_fewshot_c_train_split_3.txt',
    val_list_file='data/kinetics400_fewshot_C/kinetics_video_val_list.txt',
    use_res=True,

    lr=1e-3,
    min_lr=0,
    warmup_epochs=0,
    text_lr=1e-5,
    no_fusion=True,

    epochs=50,
    batch_size=int(128),
    is_video=True,
    num_segments=16,
    new_length=1,
    select_num=50,

    repeated_aug=False,
    clip_ms=True,
    io_backend='disk',
    only_video=False,
    find_unused_parameters=False,
    broadcast_bn_buffer=True,
    num_classes=400,

    opt='adamw',
    sim_header='Transf',
    dropout=0.,
    emb_dropout=0.,
    place='blockres',
    joint=False,
    tsm=False,
    T=16,
    consider_fusion_module=False
)